name = "vygalaxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "galaxy-db"
database_id = "9b829d2d-7bb2-4674-88b7-a33cc9504e81"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "galaxy-media"

[vars]
PAYPAL_CLIENT_ID = "AbjOkZiNZd83Or_YmzrSZ3QR6e5rdPFjtCPr_DdUCvlu5C9YjOe4EHOfVSuBcsrArWqauV2bBNdKNFvO"
PAYPAL_SK = "EJxNRKqalrsv38yCM6QiWq2KcLGun4tjxh6EpG37dvRpHXgqt06FrH55RkW0n4pGAP8Fb5UM-q4vrECa"
