name = "vygalaxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "galaxy-db"
database_id = "9b829d2d-7bb2-4674-88b7-a33cc9504e81"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "galaxy-media"

[triggers]
crons = ["0 6 1 * *", "0 3 * * *"]
